version: '3'
services:
  nuxt-app:
    image: node:18
    container_name: nuxt-app
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - '3000:3000'
    command: >
      sh -c "npm install && npm run dev"
